### ISSUE TITLE
Hope to get the initialization process of the entire contract project,thanks

### ISSUE THREAD

**Issue by GreatMartial** [SubDAO-Network/subDAO-contracts#4]
Hello! Can you provide the instantiation steps for the complete use of all the contracts under the project here, because there seems to be a dependency between the contracts(For example, the claim of the redpacket contract requires erc20 address), and I encountered this kind of error. 

thanks！

**Comment by GreatMartial** [comment]
It would be better if you could provide a simple example of calling each contract method. 
Because of multiple single-contract exec calls, I encountered an unsolvable problem.
thanks！

**Comment by lastbiter** [comment]
Will do

**Comment by lastbiter** [comment]
https://github.com/SubDAO-Network/docs/blob/main/deployment/deployment_guide.md @GreatMartial

**Comment by GreatMartial** [comment]
> https://github.com/SubDAO-Network/docs/blob/main/deployment/deployment_guide.md @GreatMartial

thank you for your reply👍
